from __future__ import annotations

import os
import json
import requests
import tools

SYSTEM_PROMPT = """\
You are Skylark Drones' internal Business Intelligence assistant. Founders \
and execs ask you questions about the sales pipeline (Deals board) and \
project execution (Work Orders board), both live on monday.com.

Rules:
1. Never answer a numeric/business question from memory or assumption - \
   always call get_deals and/or get_work_orders (or generate_leadership_report \
   for a full update) to pull live data first.
2. The data is known to be messy: missing values, inconsistent formats, and \
   occasional bad rows. When a tool result includes data_quality_caveats, \
   weave the relevant ones into your answer in plain language - don't hide \
   them, and don't let them silently skew a number without a note.
3. If a question is genuinely ambiguous (e.g. "this quarter" with no year, \
   or a sector name that doesn't clearly match one of the real sector \
   values), ask a brief clarifying question before running the tools - \
   don't guess silently on something that would change the answer.
4. Give the founder a real answer with the actual number and brief context \
   (e.g. "why", "compared to what"), not just a raw dump of records. You may \
   quote a handful of specific deals/work orders by name when it helps, but \
   don't paste large raw tables - summarize.
5. If asked for a "leadership update", "executive summary", or similar, use \
   generate_leadership_report and present its output, lightly introduced.
6. If a tool result is empty or a filter matched nothing, say so plainly \
   rather than inventing a plausible-sounding number.
"""

def _get_gemini_tools():
    declarations = []
    for t in tools.TOOLS_SCHEMA:
        declarations.append({
            "name": t["name"],
            "description": t["description"],
            "parameters": t["input_schema"]
        })
    return [{"function_declarations": declarations}]

def _run_gemini_turn(conversation: list[dict], board_ids: dict, session_cache: dict, api_key: str) -> str:
    """Executes multi-turn conversation with tool-calling using Google Gemini API."""
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={api_key}"
    
    # Format contents for Gemini
    gemini_contents = []
    for msg in conversation:
        role = "user" if msg["role"] == "user" else "model"
        if isinstance(msg["content"], str):
            gemini_contents.append({"role": role, "parts": [{"text": msg["content"]}]})
        elif isinstance(msg["content"], list):
            parts = []
            for item in msg["content"]:
                if isinstance(item, dict) and item.get("type") == "tool_result":
                    parts.append({
                        "functionResponse": {
                            "name": item.get("name", "tool"),
                            "response": {"output": item.get("content", "")}
                        }
                    })
                elif isinstance(item, dict) and item.get("type") == "tool_use":
                    parts.append({
                        "functionCall": {
                            "name": item.get("name"),
                            "args": item.get("input", {})
                        }
                    })
                elif isinstance(item, str):
                    parts.append({"text": item})
            if parts:
                gemini_contents.append({"role": role, "parts": parts})

    while True:
        payload = {
            "contents": gemini_contents,
            "system_instruction": {"parts": [{"text": SYSTEM_PROMPT}]},
            "tools": _get_gemini_tools(),
            "generationConfig": {"temperature": 0.2, "maxOutputTokens": 1500}
        }
        
        resp = requests.post(url, json=payload, headers={"Content-Type": "application/json"}, timeout=30)
        if resp.status_code != 200:
            return f"Gemini API Error ({resp.status_code}): {resp.text}"

        res_data = resp.json()
        candidates = res_data.get("candidates", [])
        if not candidates:
            return "No response generated by Gemini."

        candidate = candidates[0]
        content = candidate.get("content", {})
        parts = content.get("parts", [])

        # Check for function calls
        function_calls = [p["functionCall"] for p in parts if "functionCall" in p]
        
        if not function_calls:
            # Final text response
            text_parts = [p.get("text", "") for p in parts if "text" in p]
            final_text = "\n".join(text_parts).strip()
            conversation.append({"role": "assistant", "content": final_text})
            return final_text

        # Record assistant tool call in gemini_contents
        gemini_contents.append({"role": "model", "parts": parts})
        
        # Execute each function call
        fn_responses = []
        for fc in function_calls:
            fn_name = fc.get("name")
            fn_args = fc.get("args", {})
            tool_res_str = tools.run_tool(fn_name, fn_args, board_ids, session_cache)
            fn_responses.append({
                "functionResponse": {
                    "name": fn_name,
                    "response": {"output": tool_res_str}
                }
            })

        # Append function responses as user turn in Gemini contents
        gemini_contents.append({"role": "user", "parts": fn_responses})

def _run_anthropic_turn(conversation: list[dict], board_ids: dict, session_cache: dict, api_key: str) -> str:
    import anthropic
    client = anthropic.Anthropic(api_key=api_key)
    model = "claude-sonnet-5"

    while True:
        response = client.messages.create(
            model=model,
            max_tokens=1500,
            system=SYSTEM_PROMPT,
            tools=tools.TOOLS_SCHEMA,
            messages=conversation,
        )

        conversation.append({"role": "assistant", "content": response.content})

        if response.stop_reason != "tool_use":
            text_parts = [b.text for b in response.content if b.type == "text"]
            return "\n".join(text_parts).strip()

        tool_results = []
        for block in response.content:
            if block.type != "tool_use":
                continue
            result_str = tools.run_tool(block.name, block.input, board_ids, session_cache)
            tool_results.append({
                "type": "tool_result",
                "tool_use_id": block.id,
                "name": block.name,
                "content": result_str,
            })

        conversation.append({"role": "user", "content": tool_results})

def run_agent_turn(conversation: list[dict], board_ids: dict, session_cache: dict) -> str:
    gemini_key = os.environ.get("GEMINI_API_KEY")
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY")

    if gemini_key:
        return _run_gemini_turn(conversation, board_ids, session_cache, gemini_key)
    elif anthropic_key:
        return _run_anthropic_turn(conversation, board_ids, session_cache, anthropic_key)
    else:
        raise RuntimeError("No LLM API Key found! Set GEMINI_API_KEY or ANTHROPIC_API_KEY in secrets.toml or environment.")
